lines = 'PeggyMasukuputthefinishingtouchesonthewelcomesigntoherhomesteadinsouthwesternZimbabwesMatobodistrictShesurveyedherhandiworksixmonthsofdesigningandpaintingherhutsinanticipationofanannualcompetitionMyBeautifulHomewhichrecognisesthemostbeautifultraditionallydecoratedhomesinthedistrict'
print(len(lines))



